### ISSUE TITLE
Unable to run "play_media"

### ISSUE THREAD

**Issue by XusBadia** [custom-components/media_player.braviatv_psk#1]
I've been trying to run the "play_media" services but I keep getting this error. All other services ("turn_on", "volume_down"...) work fine, but the "play_media" won't.

Here's the log I get:

> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 279, in _handle_service_platform_call
>     await func(entity, data)
>   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 592, in play_media
>     raise NotImplementedError()
> NotImplementedError

**Comment by XusBadia** [comment]
I thought I had removed the original "braviatv" component, but I didn't... Removing it fixed the issue... Oups!
