### ISSUE TITLE
Doesn't work after update to 0.94

### ISSUE THREAD

**Issue by lasse9000** [custom-components/media_player.braviatv_psk#13]
Hello

It doesn't work on all 3 of my tv. Do I need to change anything?

Thanks

2019-06-06 12:25:41 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform braviatv_psk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
SLOW_SETUP_MAX_WAIT)
File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
return fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/braviatv_psk/media_player.py", line 89, in setup_platform
[BraviaTVDevice(host, psk, mac, name, amp, android, source_filter)])
File "/config/custom_components/braviatv_psk/media_player.py", line 98, in init
from braviapsk import sony_bravia_psk
ModuleNotFoundError: No module named 'braviapsk'
2019-06-06 12:25:41 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform braviatv_psk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
SLOW_SETUP_MAX_WAIT)
File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
return fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/braviatv_psk/media_player.py", line 89, in setup_platform
[BraviaTVDevice(host, psk, mac, name, amp, android, source_filter)])
File "/config/custom_components/braviatv_psk/media_player.py", line 98, in init
from braviapsk import sony_bravia_psk
ModuleNotFoundError: No module named 'braviapsk'
2019-06-06 12:25:41 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform braviatv_psk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
SLOW_SETUP_MAX_WAIT)
File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
return fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/braviatv_psk/media_player.py", line 89, in setup_platform
[BraviaTVDevice(host, psk, mac, name, amp, android, source_filter)])
File "/config/custom_components/braviatv_psk/media_player.py", line 98, in init
from braviapsk import sony_bravia_psk
ModuleNotFoundError: No module named 'braviapsk'

**Comment by lasse9000** [comment]
Copyed the new files and it works again.
