### ISSUE TITLE
Error Messge

### ISSUE THREAD

**Issue by ericliu1234567** [custom-components/media_player.braviatv_psk#6]
Hi friend,

My bravia will turn on and off suddenly in HA (ref to picture 1), but TV actually didn’t have action ,we found that the below error message, could you pls help to solve it? Thanks!

![Picture_1](https://user-images.githubusercontent.com/49298157/56012975-60274100-5d21-11e9-8a72-9059b1925324.jpg)

2019-04-12 02:52:15 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/auth.py", line 98, in auth_middleware
    return await handler(request)
  File "/usr/src/app/homeassistant/components/http/view.py", line 112, in handle
    result = await result
  File "/usr/src/app/homeassistant/components/api/__init__.py", line 342, in post
    domain, service, data, True, self.context(request))
  File "/usr/src/app/homeassistant/core.py", line 1133, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1155, in _execute_service
    await handler.func(service_call)
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/usr/src/app/homeassistant/helpers/service.py", line 278, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/app/homeassistant/helpers/service.py", line 292, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/braviatv_psk/media_player.py", line 365, in media_pause
    self._braviarc.media_tvpause()
  File "/config/deps/lib/python3.7/site-packages/braviapsk/sony_bravia_psk.py", line 365, in media_tvpause
    self.send_req_ircc(self.get_command_code('TvPause'))
  File "/config/deps/lib/python3.7/site-packages/braviapsk/sony_bravia_psk.py", line 135, in send_req_ircc
    params + "</IRCCCode></u:X_SendIRCC></s:Body></s:Envelope>").encode("UTF-8")
TypeError: can only concatenate str (not "NoneType") to str

**Comment by gerard33** [comment]
Did you try to pause the TV channel when this happens?
Looks like `TvPause` is not working on your TV. Can you check if your TV supports that?

**Comment by ericliu1234567** [comment]
I never pause the tv channel, it will happen suddenly and I didn’t have control the tv at that moment. Is it relatd to WiFi network issue? 

my Bravia model are KD-65X9000E with latest version. 

Thanks!!

**Comment by gerard33** [comment]
That's strange. I have never had this issue.
Can you connect your TV with a LAN cable to see if the issue occurs then as well?
